server:
  port: 8080

web:
  upload-path: F:\\videoapp_upload\\

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/video_app?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8            #查出来的 Date 时间与数据库中的时间相差 8 个小时
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB     #上传单个文件的最大值
      max-request-size: 10GB  #上传总文件的最大值
      resolve-lazily: false   # 是否延迟解析multipart请求
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #使用驼峰命名

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 259200 #JWT的超期限时间(60*60*24*3) 三天
  expirationRefreshToken: 54432000 #JWT的超期限时间(60*60*24*90*1000)
  tokenHead: Bearer #JWT负载中拿到开头